**Data cleaning assignment**

Name: Azizur Rahman

Date: 15 june 2026

Dataset info :

*   name : dirty_dataset.csv
*   size : 20,300 rows x 15 columns

import important library

In [74]:
import pandas as pd
import numpy as np

read the dataset

In [2]:
df = pd.read_csv("/content/dirty_dataset.csv")
df.head(10)
df.tail(10)

,employee_id,name,age,salary,join_date,department,gender,country,city,weight_kg,is_active,review,price,weight_kg_duplicate,target
20290,16444,Charlie I.,60.0,93596,2011-01-24,NaN,Woman,BANGLADESH,Chittagong,116.2,True,Good value for money.,79.97,NaN,0
20291,8369,John W.,24.0,95199,2024-03-28,hr,NaN,U.K.,Khulna,83kg,True,"Excellent product, highly recommend!",336.72,NaN,0
20292,16834,Grace F.,50.0,111758,2019-02-04,Engineering,Female,usa,Chittagong,69.4,False,Would buy again without hesitation.,472.76,NaN,0
20293,12274,Eve F.,50.0,32285,2016-03-21,Mrketing,Female,Bangladesh,NaN,129.4,False,Very satisfied with the quality.,234.92,NaN,0
20294,16440,Charlie W.,37.0,46333,01-27-2016,hr,MALE,U.S.A,Rajshahi,58kg,False,NaN,8.68,NaN,0
20295,19842,Frank N.,27.0,9999999,2010-06-21,engineering,Female,U.K.,Chittagong,93.7,False,Delivery was fast and packaging great.,$199.19,NaN,0
20296,1769,Frank N.,45.0,31616,2021-01-11,hr,F,U.K.,Khulna,NaN,False,Product met all expectations.,223.39,NaN,0
20297,9930,Hasan A.,30.0,70125,2013-07-07,Engineering,Woman,bd,Khulna,116.3,True,Would buy again without hesitation.,68.16,NaN,0
20298,3241,Frank D.,58.0,40120,2022-03-25,SALES,M,UK,Rajshahi,72.0,True,NaN,90.83,NaN,0
20299,13498,Alice X.,NaN,114722,2023-08-12,HR,Man,UK,Khulna,74.0,False,NaN,142.13,NaN,0


**Task 01 Missing Values (NaN, Empty Strings)**


1. Run df.isnull().sum() to count missing values per column.
2. Numeric columns (age, salary, price, weight_kg): fill with median.
3. Categorical columns (department, gender, country, city): fill with mode.
4. Date column (join_date): forward fill or fill with most frequent date.
5. review column: fill with &#39;No Review&#39;.
6. is_active: fill with False (conservative approach).
7. Verify: run df.isnull().sum() again — all should be 0.

**1. count missing values per column**

In [3]:
df.isnull().sum()

employee_id                0
name                       0
age                      621
salary                   610
join_date                810
department               857
gender                  1632
country                  608
city                     604
weight_kg                643
is_active                586
review                  1465
price                    446
weight_kg_duplicate    20300
target                     0
dtype: int64

**2.Numeric columns** :(age, salary, price, weight_kg): fill with median.

In [4]:
dfFirstCopy = df.copy()

In [5]:
dfFirstCopy.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20300 entries, 0 to 20299
Data columns (total 15 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   employee_id          20300 non-null  int64
 1   name                 20300 non-null  object
 2   age                  19679 non-null  float64
 3   salary               19690 non-null  object
 4   join_date            19490 non-null  object
 5   department           19443 non-null  object
 6   gender               18668 non-null  object
 7   country              19692 non-null  object
 8   city                 19696 non-null  object
 9   weight_kg            19657 non-null  object
 10  is_active            19714 non-null  object
 11  review               18835 non-null  object
 12  price                19854 non-null  object
 13  weight_kg_duplicate  0 non-null      float64
 14  target               20300 non-null  int64
dtypes: float64(2), int64(2), object(11)
memory usage: 2.3+ MB

There are some columns that are object,so firstly we need to change it

In [6]:
col_to_change = ['age', 'salary', 'price', 'weight_kg']
for col in col_to_change:
  dfFirstCopy[col] = pd.to_numeric(dfFirstCopy[col], errors='coerce')

now convert all null value to median

In [7]:
col_to_fill = ['age', 'salary', 'price', 'weight_kg']
for col in col_to_fill:
  dfFirstCopy[col].fillna(dfFirstCopy[col].median(), inplace=True)

/tmp/ipykernel_905/3177458301.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  dfFirstCopy[col].fillna(dfFirstCopy[col].median(), inplace=True)

check ->is it solve the numeric columns null value problem

In [8]:
dfFirstCopy.isnull().sum()

employee_id                0
name                       0
age                        0
salary                     0
join_date                810
department               857
gender                  1632
country                  608
city                     604
weight_kg                  0
is_active                586
review                  1465
price                      0
weight_kg_duplicate    20300
target                     0
dtype: int64

**3.Categorical columns**: (department, gender, country, city): fill with mode.

In [9]:
categorical_col = ['department','gender','country','city']
for col in categorical_col:
  dfFirstCopy[col] = dfFirstCopy[col].fillna(dfFirstCopy[col].mode()[0])

check ->is it solve the categorical columns null value problem

In [10]:
dfFirstCopy.isnull().sum()

employee_id                0
name                       0
age                        0
salary                     0
join_date                810
department                 0
gender                     0
country                    0
city                       0
weight_kg                  0
is_active                586
review                  1465
price                      0
weight_kg_duplicate    20300
target                     0
dtype: int64

**4. Date column (join_date): forward fill or fill with most frequent date.**

In [11]:
dfFirstCopy.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20300 entries, 0 to 20299
Data columns (total 15 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   employee_id          20300 non-null  int64
 1   name                 20300 non-null  object
 2   age                  20300 non-null  float64
 3   salary               20300 non-null  float64
 4   join_date            19490 non-null  object
 5   department           20300 non-null  object
 6   gender               20300 non-null  object
 7   country              20300 non-null  object
 8   city                 20300 non-null  object
 9   weight_kg            20300 non-null  float64
 10  is_active            19714 non-null  object
 11  review               18835 non-null  object
 12  price                20300 non-null  float64
 13  weight_kg_duplicate  0 non-null      float64
 14  target               20300 non-null  int64
dtypes: float64(5), int64(2), object(8)
memory usage: 2.3+ MB

join_date column data type was object thats why i need to change it

In [12]:
dfFirstCopy['join_date'] = pd.to_datetime(dfFirstCopy['join_date'], format='mixed', dayfirst=True)

fill it with forward fill -> ffill

In [13]:
dfFirstCopy['join_date'] = dfFirstCopy['join_date'].ffill()

check ->is it solve the date columns null value problem

In [14]:
dfFirstCopy.isnull().sum()

employee_id                0
name                       0
age                        0
salary                     0
join_date                  0
department                 0
gender                     0
country                    0
city                       0
weight_kg                  0
is_active                586
review                  1465
price                      0
weight_kg_duplicate    20300
target                     0
dtype: int64

**5. review column** : fill with 'No Review'

In [15]:
dfFirstCopy['review'] = dfFirstCopy['review'].fillna('No Review')

check ->is it solve the review column null value problem

In [16]:
dfFirstCopy.isnull().sum()

employee_id                0
name                       0
age                        0
salary                     0
join_date                  0
department                 0
gender                     0
country                    0
city                       0
weight_kg                  0
is_active                586
review                     0
price                      0
weight_kg_duplicate    20300
target                     0
dtype: int64

**6. is_active:** fill with False (conservative approach).

In [17]:
dfFirstCopy['is_active'] = dfFirstCopy['is_active'].fillna(False)

check ->is it solve the is_active column null value problem

In [18]:
dfFirstCopy.isnull().sum()

employee_id                0
name                       0
age                        0
salary                     0
join_date                  0
department                 0
gender                     0
country                    0
city                       0
weight_kg                  0
is_active                  0
review                     0
price                      0
weight_kg_duplicate    20300
target                     0
dtype: int64

**Task 02: Duplicate Rows**

8. Run df.duplicated().sum() to count duplicates.
9. Preview duplicates: df[df.duplicated()]
10. Remove duplicates: df.drop_duplicates(inplace=True)
11. Verify: compare df.shape before and after.
Hint: Use df.drop_duplicates()

In [19]:
duplicate_counts = dfFirstCopy.duplicated().sum()
print(f'Number of duplicate rows : {duplicate_counts}')

Number of duplicate rows : 291

**preview of duplicate rows**

In [20]:
preiview_of_duplicate = dfFirstCopy[dfFirstCopy.duplicated()]
print(preiview_of_duplicate)

       employee_id        name    age    salary  join_date   department  \
1302         10364    Frank O.   24.0  112578.0 2010-09-10           HR
1834         16035    Hasan V.   53.0    -500.0 2017-03-01    Marketing
2338         12369    Hasan D.  200.0   35149.0 2023-05-30        SALES
2469         13108    Diana V.   43.0   88859.0 2016-07-21    Marketing
2784          7983    Grace G.   32.0   75294.0 2019-02-01  engineering
...            ...         ...    ...       ...        ...          ...
20110        13509  Charlie S.   34.0  106326.0 2016-06-20       Finace
20140         2388      Eve A.   35.0   98091.0 2017-04-22        SALES
20154         2689     John O.   46.0   45615.0 2019-12-04           hr
20173         5188  Charlie J.   46.0   75294.0 2017-04-03           HR
20227         4518    Grace R.   54.0   66484.0 2012-06-01    Marketing

       gender        country        city  weight_kg is_active  \
1302        M             BD        Dhka       95.8      True
1834   female     BANGLADESH  Chittagong       48.2     False
2338      Man        America      Sylhet      118.4         0
2469     Male  United States      Khulna       73.8      True
2784      Man           U.K.      Khulna       60.2      True
...       ...            ...         ...        ...       ...
20110     Man          U.S.A      Slyhet      112.3     False
20140       M        America      Slyhet       90.4     False
20154       F            usa    Rajshahi       87.1     False
20173    Male     BANGLADESH  Chittagong       73.0      True
20227       M     BANGLADESH      Khulna      116.2      True

                                       review   price  weight_kg_duplicate  \
1302   Delivery was fast and packaging great.   22.75                  NaN
1834            Product met all expectations.  385.13                  NaN
2338                    Good value for money.  219.18                  NaN
2469                                     good  430.17                  NaN
2784     Excellent product, highly recommend!  245.23                  NaN
...                                       ...     ...                  ...
20110                                    fine  340.03                  NaN
20140                   Good value for money.  451.34                  NaN
20154     Would buy again without hesitation.  341.28                  NaN
20173                                     bad  419.32                  NaN
20227           Product met all expectations.  249.01                  NaN

       target
1302        0
1834        0
2338        0
2469        0
2784        0
...       ...
20110       0
20140       0
20154       0
20173       0
20227       0

[291 rows x 15 columns]

**Remove Duplicates**

In [21]:
dfFirstCopy.drop_duplicates(inplace=True)

**check duplicates value**

In [22]:
dfFirstCopy.duplicated().sum()

np.int64(0)

**verify: compare df.shape before and after**

before

In [23]:
df.shape

(20300, 15)

after

In [24]:
dfFirstCopy.shape

(20009, 15)

**Task 03 Duplicate IDs**

12. Count: df['employee_id'].duplicated().sum()
13. View: df[df['employee_id'].duplicated(keep=False)]
14. Option A: keep first occurrence — df.drop_duplicates(subset=['employee_id], keep='first')
15. Option B: assign new unique IDs — df['employee_id'] = range(1, len(df)+1)
16. Verify: assert df['employee_id'].duplicated().sum() == 0

**12 sum of the employee id duplicated**

In [25]:
dfFirstCopy['employee_id'].duplicated().sum()

np.int64(208)

**13. view employee_id column which are duplicate**

In [26]:
dfFirstCopy[dfFirstCopy['employee_id'].duplicated(keep=False)]

,employee_id,name,age,salary,join_date,department,gender,country,city,weight_kg,is_active,review,price,weight_kg_duplicate,target
29,250,Frank U.,56.0,90635.0,2013-05-12,Sales,male,Bangladesh,Dhaka,107.3,0,Would buy again without hesitation.,342.24,NaN,1
40,49,John L.,58.0,50810.0,2024-07-22,hr,FEMALE,U.K.,Dhakka,108.8,False,"Excellent product, highly recommend!",83.46,NaN,0
75,48,Ira E.,0.0,101013.0,2013-08-28,engineering,MALE,BD,Dhakka,87.1,0,Good value for money.,318.78,NaN,0
196,436,Charlie S.,29.0,54295.0,2020-08-27,Mrketing,M,us,Chittagongg,75.9,False,Product met all expectations.,265.25,NaN,0
270,86,Bob U.,36.0,61688.0,2012-11-23,engineering,M,bd,Sylhet,91.7,False,na,167.05,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20016,207,Bob M.,63.0,73657.0,2013-10-08,Mrketing,M,USA,Rajshahi,125.5,False,Very satisfied with the quality.,167.18,NaN,0
20072,435,Charlie U.,31.0,112727.0,2016-04-15,engineering,MALE,U.K.,Rajshahi,119.0,1,Good value for money.,242.44,NaN,0
20104,427,Frank U.,33.0,35686.0,2014-03-21,Mrketing,M,usa,Rajshahi,73.8,True,Good value for money.,396.43,NaN,0
20267,35,Eve L.,55.0,40160.0,2015-12-13,Finance,Male,U.K.,Dhaka,61.0,True,Very satisfied with the quality.,106.40,NaN,0
20289,289,Frank C.,58.0,95829.0,2011-10-28,HR,Woman,United States,Khulna,93.2,True,Very satisfied with the quality.,123.17,NaN,0

**14 Option A:** keep first occurence

---


for that i create a copy of dfFirstCopy

In [27]:
dfOptionA = dfFirstCopy.copy()

In [28]:
dfOptionA.drop_duplicates(subset=['employee_id'], keep='first', inplace=True)

**15 Option B :**assign new unique IDs

---
for that we can change on the dfFirstCopy

In [29]:
dfFirstCopy['employee_id'] = range(1, len(dfFirstCopy) + 1)

**verify it **

In [30]:
dfFirstCopy['employee_id'].duplicated().sum()

np.int64(0)

In [31]:
dfOptionA['employee_id'].duplicated().sum()

np.int64(0)

**Task 04 Wrong Date Formats**

17. Check dtype: df['join_date'].dtype — will be object.
18. Convert: pd.to_datetime(df['join_date'], infer_datetime_format=True, errors='coerce')
19. errors='coerce' turns unrecognized formats into NaT.
20. Handle NaT values: fill with median date.
21. Standardize output: df['join_date'].dt.strftime('%Y-%m-%d')
22. Verify dtype: df['join_date'].dtype — should be datetime64.
Hint: Use pd.to_datetime() with infer_datetime_format=True

I already changed the data type of join_date column when I solved the missing value problem on it

For practicing, I am creating a new df which is dfSecondCopy of df

In [32]:
dfSecondCopy = df.copy()

In [33]:
dfSecondCopy['join_date'].dtype

dtype('O')

In [34]:
dfSecondCopy['join_date'] = pd.to_datetime(dfSecondCopy['join_date'], infer_datetime_format=True, errors='coerce')

/tmp/ipykernel_905/1241420720.py:1: UserWarning: The argument 'infer_datetime_format' is deprecated and will be removed in a future version. A strict version of it is now the default, see https://pandas.pydata.org/pdeps/0004-consistent-to-datetime-parsing.html. You can safely remove this argument.
  dfSecondCopy['join_date'] = pd.to_datetime(dfSecondCopy['join_date'], infer_datetime_format=True, errors='coerce')

In [35]:
dfSecondCopy['join_date'].dtype

dtype('<M8[ns]')

In [36]:
dfSecondCopy['join_date'].isna().sum()

np.int64(3366)

**20 handle NaT values:fill with median date**

In [37]:
median_date = dfSecondCopy['join_date'].median()
dfSecondCopy['join_date'].fillna(median_date, inplace=True)

/tmp/ipykernel_905/1100241568.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  dfSecondCopy['join_date'].fillna(median_date, inplace=True)

**21 Standardize output: df['join_date'].dt.strftime('%Y-%m-%d')**

In [38]:
dfSecondCopy['join_date'] = dfSecondCopy['join_date'].dt.strftime('%Y-%m-%d')

**strftime -> this convert the column back to object**

**22 verify dtype**

In [39]:
dfSecondCopy['join_date'].dtype

dtype('O')

convert it again

In [40]:
dfFirstCopy['join_date'] = pd.to_datetime(dfFirstCopy['join_date'],format='%Y-%m-%d')

In [41]:
dfSecondCopy['join_date'].dtype

dtype('O')

**Task 05 Numeric Stored as String**


---


23. Check dtype: df['salary'].dtype — will be object.
24. salary: use str.replace
25. weight_kg: df['weight_kg'].str.replace('kg', regex=False).astype(float)
26. price: same approach — strip $ then convert to float.
27. Handle errors: pd.to_numeric(df[df['salary'], errors='coerce')
28. Verify: df.dtypes — all three columns should be float64.

On dfFirstCopy, which is already a float data type, I changed it at task 01 when solving the missing values problem.thats why i am using dfSecondCopy

In [42]:
dfSecondCopy[['salary', 'weight_kg', 'price']].dtypes

salary       object
weight_kg    object
price        object
dtype: object

**24. Clean the salary column**

In [43]:
dfSecondCopy['salary'] = dfSecondCopy['salary'].str.replace('$','','regex = false').astype(float)

**25. Clean the weignt_kg column**

In [44]:
dfSecondCopy['weight_kg'] = dfSecondCopy['weight_kg'].str.replace('kg', '', regex=False).astype(float)

**26.Clean the price column**

In [45]:
dfSecondCopy['price'] = dfSecondCopy['price'].str.replace('$', '', regex=False).astype(float)

**27. handle errors**

In [46]:
dfSecondCopy['price'] = pd.to_numeric(dfSecondCopy['price'], errors='coerce')

In [47]:
dfSecondCopy['salary'] = pd.to_numeric(dfSecondCopy['salary'], errors='coerce')

In [48]:
dfSecondCopy['weight_kg'] = pd.to_numeric(dfSecondCopy['weight_kg'], errors='coerce')

**verify: df.dtypes — all three columns should be float64.**

In [49]:
dfSecondCopy[['salary', 'weight_kg', 'price']].dtypes

salary       float64
weight_kg    float64
price        float64
dtype: object

**Task 06 Inconsistent Labels**

---

29. Inspect: df['country'].value_counts() to see all unique values.
30. Build a mapping dictionary for country:
31. country_map = {'USA':'United States','U.S.A':'United States','America':'United States', ...}
32. Apply: df['country'] = df['country'].map(country_map).fillna(df['country'])
33. gender: df['gender'].str.lower() then map to standard values.
34. department: df['department'].str.strip().str.title() then fix spellings.
35. Verify: run value_counts() on each column after fixing.

**29. to see all uniques values**

In [50]:
dfSecondCopy['country'].value_counts()

country
USA               1550
usa               1549
U.K.              1548
BD                1534
Bangladesh        1530
U.S.A             1525
us                1514
UK                1514
United States     1507
America           1505
BANGLADESH        1502
bd                1466
United Kingdom    1448
Name: count, dtype: int64

In [51]:
dfSecondCopy['gender'].value_counts()

gender
M         1951
Woman     1893
male      1877
Man       1872
Female    1869
female    1865
Male      1859
MALE      1849
F         1833
FEMALE    1800
Name: count, dtype: int64

In [52]:
dfSecondCopy['department'].value_counts()

department
Sales          1995
Engineering    1977
hr             1959
Finace         1953
Marketing      1945
HR             1943
Mrketing       1937
engineering    1918
SALES          1910
Finance        1906
Name: count, dtype: int64

**30. build a mapping dictionary for country**

In [53]:
country_map = {
    'USA': 'United States',
    'U.S.A': 'United States',
    'U.S.A.': 'United States',
    'America': 'United States',
    'us': 'United States',
    'UK': 'United Kingdom',
    'U.K': 'United Kingdom',
    'England': 'United Kingdom',
    'Bangladesh ': 'Bangladesh'
}

**31. country_map**

In [54]:
dfSecondCopy['country'] = df['country'].replace(country_map)

**32. apply fillna**

In [55]:
dfSecondCopy['country'] = dfSecondCopy['country'].fillna(df['country'])

**33. gender set to all lower**

In [56]:
dfSecondCopy['gender'] = dfSecondCopy['gender'].str.strip().str.lower()

map to standard values

In [57]:
gender_map = {
    'm': 'Male',
    'male': 'Male',
    'f': 'Female',
    'female': 'Female',
    'man': 'Male',
    'woman': 'Female'
}

dfSecondCopy['gender'] = dfSecondCopy['gender'].replace(gender_map)

**34. clean department column**

In [58]:
dfSecondCopy['department'] = dfSecondCopy['department'].str.strip().str.title()

fix spelling issue and map to standard values

In [59]:
dept_map = {
    'Hr': 'HR',
    'H R': 'HR',
    'It': 'IT',
    'I T': 'IT',
    'Finanace': 'Finance'
}

dfSecondCopy['department'] = dfSecondCopy['department'].replace(dept_map)

**verify**

In [60]:
print(dfSecondCopy['country'].value_counts())
print(dfSecondCopy['gender'].value_counts())
print(dfSecondCopy['department'].value_counts())

country
United States     7601
United Kingdom    2962
usa               1549
U.K.              1548
BD                1534
Bangladesh        1530
BANGLADESH        1502
bd                1466
Name: count, dtype: int64
gender
Male      9408
Female    9260
Name: count, dtype: int64
department
Sales          3905
HR             3902
Engineering    3895
Finace         1953
Marketing      1945
Mrketing       1937
Finance        1906
Name: count, dtype: int64

**Task 7: Spelling Mistakes**

---

36. Inspect: df['city'].value_counts() to find all misspelled cities.
37. Build correction dictionary:
38. city_fix
39. Apply: df['city'] = df['city'].replace(city_fix)
40. Same approach for department:
41. Verify: df['city'].unique() — should only show correct city names.

**36. Inspect the city column**

In [63]:
dfSecondCopy['city'].value_counts()

city
Khulna         3815
Rajshahi       3337
Sylhet         3268
Dhaka          3166
Chittagong     3166
Slyhet          525
Dhka            493
Rajshai         490
Dhakka          480
Chittagongg     479
Chitagong       477
Name: count, dtype: int64

**37. build correction dictionary**

In [64]:
city_fix = {
    'Dhka': 'Dhaka',
    'Dhakka': 'Dhaka',
    'Chitagong': 'Chittagong',
    'Chittagongg': 'Chittagong',
    'Slyhet': 'Sylhet',
    'Rajshai': 'Rajshahi'
}

**39. Apply: that fix dictionary**

In [65]:
dfSecondCopy['city'] = dfSecondCopy['city'].replace(city_fix)

**40. same approach for department**

In [66]:
department_fix = {
    'Mrketing': 'Marketing',
    'Finace': 'Finance'
}

In [67]:
dfSecondCopy['department'] = dfSecondCopy['department'].replace(department_fix)

**41. Verify it**

In [68]:
dfSecondCopy['city'].unique()

array(['Sylhet', 'Chittagong', 'Khulna', 'Dhaka', 'Rajshahi', nan],
      dtype=object)

In [69]:
dfSecondCopy['city'].value_counts()

city
Dhaka         4139
Chittagong    4122
Rajshahi      3827
Khulna        3815
Sylhet        3793
Name: count, dtype: int64

In [70]:
dfSecondCopy['department'].unique()

array(['Sales', 'Engineering', 'HR', 'Marketing', 'Finance', nan],
      dtype=object)

In [71]:
dfSecondCopy['department'].value_counts()

department
Sales          3905
HR             3902
Engineering    3895
Marketing      3882
Finance        3859
Name: count, dtype: int64

**Task 08 Outliers**


---

42. Explore: df['salary'].describe() to see min, max, mean, std.
43. Visualize: df['salary'].plot(kind='bow') or plt.boxplot(df['salary'])
44. Calculate IQR: Q1 = df['salary'].quantile(0.25), Q3 = df['salary'].quantile(0.75)
45. IQR = Q3 - Q1
46. Bounds: lower = Q1 - 1.5*IQR | upper = Q3 + 1.5*IQR
47. Identify outliers: df[df['salary'] > upper] or df[df['salary'] < lower]
48. Cap outliers: df['salary'] = df['salary'].clip(lower, upper)
49. Verify: run describe() again and compare max/min values.
Hint: IQR method + df.clip(lower, upper)

**Task 42: Explore the salary column**

In [78]:
dfFirstCopy['salary'].describe()

count    2.000900e+04
mean     2.304288e+05
std      1.235861e+06
min     -5.000000e+02
25%      5.417900e+04
50%      7.529400e+04
75%      9.635400e+04
max      9.999999e+06
Name: salary, dtype: float64